### ISSUE TITLE
ERROR: Failed to generate the initramfs

### ISSUE THREAD

**Issue by hervyqa** [void-linux/void-mklive#257]
Failed to create image (base) with latest kernel.
cc @leahneukirchen

## Steps to reproduce
```
make
sudo ./build-x86-images.sh -a x86_64 -b base
```

## Result
```
[4/9] Generating initramfs image (xz)...
dracut: Cannot find module directory /lib/modules/2021.07.21_1/
dracut: and --no-kernel was not specified
ERROR: Failed to generate the initramfs
```

**Comment by classabbyamp** [comment]
heh, this was caused by https://github.com/void-linux/void-packages/pull/36659

`linux` hadn't been updated since that happened until just recently, so it didn't appear until now
